Implement getUserMedia method
instrumentisto/flutter-webrtc pull request #13
Opened 2021-11-19 11:52 UTC by logist322

## Synopsis

Этот PR имплементирует метод getUserMedia.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-12-08 06:50 UTC, logist322 commented
## FCM
```
Implement getUserMedia method (#13 #10)

Additionally:
- implement streamDispose method
```

2021-12-08 07:20 UTC, alexlapa requested changes
@logist322 ,

FIx CI first.

2021-12-08 08:25 UTC, logist322 commented
@alexlapa 

Have fixed CI. [fmt falls on a long links lines](https://github.com/rust-lang/rustfmt/issues/506).

2021-12-27 10:22 UTC, alexlapa requested changes
@logist322 ,

Sync with mainline

2021-12-28 09:20 UTC, logist322 commented
> @logist322 ,
> 
> Sync with mainline

@alexlapa done.

2021-12-30 12:44 UTC, alexlapa requested changes
@logist322 ,

Discussed, added todos.

2022-01-13 16:03 UTC, alexlapa approved these changes

2022-01-13 16:39 UTC, tyranron approved these changes

2022-01-13 16:39 UTC, tyranron commented on crates/native/src/user_media.rs
> +    ) -> anyhow::Result<Rc<VideoSource>> {
Using `anyhow` in a library code will be a bad pattern. It's better to roll out our own error types in a separate PR.

2022-01-14 07:40 UTC, merged

2022-01-14 09:43 UTC, alexlapa commented on crates/native/src/user_media.rs
> +    ) -> anyhow::Result<Rc<VideoSource>> {
@tyranron ,

Через пару-тройку PR'ов планирую этим вопросом заняться. Понятно что анврапать нельзя, бэктрэйсы надо бы прикладывать, по типизации ошибок пока еще не придумал - там все неоднозначно.

2022-01-14 15:41 UTC, tyranron commented
@logist322 please, do not forget to fully check the checklist before merging.

2022-01-14 15:54 UTC, logist322 commented
@tyranron my bad.