Implement RTCPeerConnection events
instrumentisto/flutter-webrtc pull request #27
Opened 2022-01-18 07:06 UTC by rogurotus

2022-02-04 13:04 UTC, rogurotus commented
## FCM
```
Implement `RTCPeerConnection events` (#27)

Additionally:
- `OnSignalingChange` event
- `OnStandardizedIceConnectionChange` event
- `OnConnectionChange` event
- `OnIceGatheringChange` event
- `OnNegotiationNeededEvent` event
- `OnIceCandidateError` event
- `OnIceCandidateError` event (args overload)
- `OnIceConnectionReceivingChange` event
- `OnInterestingUsage` event
- `OnIceCandidate` event
- `OnIceCandidatesRemoved` event
- `OnIceSelectedCandidatePairChanged` event
```

2022-02-09 01:42 UTC, alexlapa approved these changes

2022-02-09 09:18 UTC, tyranron commented on crates/libwebrtc-sys/src/bridge.rs
> +        kIceConnectionMax,
@rogurotus can you provide a link to that?

2022-02-09 09:33 UTC, tyranron requested changes

2022-02-09 09:33 UTC, tyranron commented on crates/libwebrtc-sys/src/bridge.rs
> +        pub fn on_connection_change(
@rogurotus here all the docs are same, which isn't quite useful. You should describe for the each function in what circumstances it completes the handler.

2022-02-09 09:33 UTC, tyranron commented on windows/src/peer_connection.cc
> +  void OnIceGatheringStateChange(const std::string& new_state) {
Similarly here, better describe in docs which event is propagated exactly.

2022-02-09 15:37 UTC, tyranron approved these changes

2022-02-09 15:50 UTC, merged