Draft: Bootstrap flutter_webrtc + rust + libwebrtc toolchain (#4)
instrumentisto/flutter-webrtc pull request #5
Opened 2021-11-03 11:51 UTC by logist322

## Synopsis

Этот PR добавляет необходимый toolchain для разработки `flutter-webrtc` под WIndows.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-05 08:32 UTC, logist322 commented
## FCM
```
Implement toolchain for desktop development under Windows (#5)

- add rust crates
- add Makefile
```

2021-11-14 21:49 UTC, alexlapa approved these changes

2021-11-15 16:17 UTC, tyranron requested changes
@logist322 one thing should be done more wisely.

2021-11-15 16:17 UTC, tyranron commented on Makefile
> +	curl -L -o temp/libwebrtc-win-x64.tar.gz $(LIBWEBRTC_URL)/libwebrtc-win-x64.tar.gz && \
This should be implementent in `build.rs` of `libwertc-sys` crate and the link controlled via env var. Keeping it in `Makefile` only complicates stuff.

2021-11-16 09:32 UTC, alexlapa requested changes

2021-11-16 09:32 UTC, alexlapa commented on crates/libwebrtc-sys/build.rs
> +    let libwebrtc_url = "https://github.com/instrumentisto/libwebrtc-bin/releases/download/97.4692.0.0-r0";
@logist322 ,

> This should be implementent in build.rs of libwertc-sys crate and the link controlled via env var.

> and the link controlled via env var

> env var

2021-11-16 09:32 UTC, alexlapa commented on crates/native/.gitignore
> +target/
@logist322 ,

Newline добавьте в конец. По хорошему, IDE'шка должна сама это уметь.

@tyranron ,

Вы этот `.gitignore` выкосили, что логично, так как крейт в вокрспейсе, и `/target` лежит не тут. Но тут немного другая история, мы в `build.rs` вот такое делаем:

```rs
    cbindgen::generate_with_config(&crate_dir, config)
        .unwrap()
        .write_to_file(format!("target/{}.hpp", package_name));
```

Ложить хедеры в корневой `target` не получается, так как переменная `CARGO_BUILD_TARGET_DIR` не прокидывается, по неизвестной причине, а хардкодить `../../target` не хочется, но можем, если Вы за такое решение.

2021-11-16 09:48 UTC, tyranron commented on crates/native/.gitignore
> +target/
@tyranron it's better to investigate what's the problem with `CARGO_BUILD_TARGET_DIR`. It should be working OK.

2021-11-16 10:53 UTC, alexlapa commented on crates/native/.gitignore
> +target/
@tyranron ,

> Make cargo export CARGO_TARGET_DIR to build.rs scripts

> Build scripts are intended to have a very scoped output (just in their OUT_DIR), and they're not currently really intended to be used as installation scripts for other sorts of files. In that sense this change was never intended for build scripts.

https://github.com/rust-lang/cargo/pull/7325#issuecomment-528365640

А `OUT_DIR` это вот: `/flutter-webrtc/target/debug/build/flutter-webrtc-native-621c22406cba9de9/out`. Бахаю `../../target`.

2021-11-16 14:50 UTC, alexlapa approved these changes

2021-11-16 17:43 UTC, tyranron approved these changes

2021-11-16 17:43 UTC, tyranron commented
@logist322 don't use `review` label on GitHub. Asking regular GitHub review is enough.

2021-11-17 11:42 UTC, merged