Add MacOS support
instrumentisto/flutter-webrtc pull request #74
Opened 2022-07-03 14:36 UTC by evdokimovs

## Synopsis

This PR adds basic support for the MacOS platform.

Screen sharing and device change notifications is not part of this PR, and will be implemented in the future PRs.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed
  
[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-07-04 15:54 UTC, evdokimovs commented
## FCM

```
Support MacOS (#74)

- bootstrap basic MacOS support
- add renderer C API for MacOS and Linux platforms
- add `renderer_c_api` and `renderer_cpp_api` Cargo features
```

2022-07-29 07:55 UTC, alexlapa approved these changes

2022-07-29 09:42 UTC, tyranron approved these changes

2022-07-29 09:48 UTC, tyranron requested changes

2022-07-29 09:48 UTC, tyranron commented on crates/native/Cargo.toml
> +renderer_c_api = ["dep:cc"]
@evdokimovs why do we have this features, which are, indeed, not additive? This complicates linting, docs, and all the stuff.

Let's strip the features out and use the `target_os =` conditions.

2022-08-04 05:14 UTC, alexlapa approved these changes

2022-08-08 14:10 UTC, tyranron approved these changes

2022-08-08 14:38 UTC, merged