Fix Bluetooth headset detection on Android
instrumentisto/flutter-webrtc pull request #78
Opened 2022-07-07 11:32 UTC by evdokimovs

Depends on #77 

## Synopsis

On Google Pixel 4 device `flutter_webrtc` started to throw `SecurityException` when trying to get `BluetoothProfile` service.

While bug researching it was discovered that for Bluetooth discovery features we need `BLUETOOTH_CONNECT` permission which requires us to ask this permission from system. ~~But this permission is granted in Android by default, so user even doesn't sees this permission request, so we can do it without breaking UX.~~ (this is true not on all devices, see _UPD 2_)

Also, while researching current bluetooth headset detection implementation better implementation was found, so now it slightly improved.

### UPD 1:

Bluetooth permission policies have been changed starting from android 12 (API 31) https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher

### UPD 2:

After some more testing on different devices it was discovered that some devices will ask user for `BLUETOOTH_CONNECT` permission explicitly, so we need implementation which doesn't requires that kind of permission. API for this was found, but it available only on SDK level >= 31, so we need to support both implementation (old one without permissions and new one available on new SDKs). This API is [`AudioManager.addOnCommunicationDeviceChangedListener`][1] and all related methods. 

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed
  
[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests
[1]: https://developer.android.com/reference/android/media/AudioManager#addOnCommunicationDeviceChangedListener(java.util.concurrent.Executor,%20android.media.AudioManager.OnCommunicationDeviceChangedListener)

2022-07-07 11:34 UTC, evdokimovs commented
## FCM

```
Fix Bluetooth headset detection on Android (#78)

- add BLUETOOTH_CONNECT permission request
- slightly improve bluetooth headset detection

Additionally:
- add indent rules to the .editorconfig for Kotlin language
```

2022-07-11 14:38 UTC, alexlapa requested changes
@evdokimovs ,

We should use new AudioManager API for SDK >= 31.

2022-10-27 09:21 UTC, alexlapa approved these changes

2023-01-19 17:44 UTC, alexlapa approved these changes

2023-01-20 10:21 UTC, tyranron approved these changes

2023-01-20 11:08 UTC, merged